matrix:

  include:
    - language: node_js
      node_js:
        - "8"
      dist: trusty
      sudo: required
      addons:
        chrome: stable
      cache:
        yarn: true
        directories:
          - node_modules
      install:
        - yarn
      script:
        - yarn test

notifications:
  email:
    - keystQuant@gmail.com
  on_success: always
  on_failure: always
