version: '3'

services:
  nginx:
    container_name: gobble_nginx
    build: ./nginx
    links:
      - gobble:gobble
    ports:
      - 3000:80
    depends_on:
      - gobble

  gobble:
    container_name: gobble_server
    build: .
    ports:
      - 3000
